import Head from 'next/head'
import { useRef } from 'react'
import { BsGithub, BsLinkedin, BsPhoneFill } from 'react-icons/bs'
import { MdEmail } from 'react-icons/md'

import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';



const layout = ({children}) =>{

  const number = useRef()
  const email = useRef()

  const clipBoard = (ref, str) => {
    console.log(number.current.value)
    navigator.clipboard.writeText(ref.current.value)
    toast(`My ${str} '${ref.current.value}' has been added to you clipBoard!`, {
      position: "bottom-right",
      autoClose: 2000,
      hideProgressBar: false,
      closeOnClick: true,
      pauseOnHover: false,
      draggable: true,
      progress: undefined,
      theme: "light",
    })
  }

  return(
    <div >
    <Head>
        <title>Ruben Wilson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
     </Head>
      <main className='bg-blue-900 min-h-screen z-0'>
        <nav className="navbar">
            <div className="flex-1">
            <a className="btn btn-ghost normal-case text-xl" href='/'>Ruben Wilson</a>
            <ToastContainer />
            </div>
            <div className="flex-none">
              <ul className="menu menu-horizontal p-0">
          
                <div className="dropdown dropdown-hover">
                <li tabIndex={0} id='contact'><a>Contact</a></li>
                <ul tabIndex={0} className="dropdown-content menu p-2 shadow bg-blue-900 rounded-box" id='contactList'>
                  <a className='p-2' href='https://github.com/ruben-wilson' id='contactGithub'><BsGithub size={50} /></a>
                  <a className='p-2' href='https://www.linkedin.com/in/ruben-wilson-6a774a254/' id='contactLinkedin'><BsLinkedin size={50} /></a>
                  <button ref={number} value='07722160086' onClick={() => clipBoard(number, 'number')} className='p-2'><BsPhoneFill size={50}/></button>
                  <button ref={email} value='rwilson-connell@yahoo.com' onClick={() => clipBoard(email, 'email')} className='p-2'><MdEmail size={50} /></button>     
                </ul>
                </div>
              <li id='aboutMe'><a href='/aboutMe'>About Me</a></li>
              <li id='myWorkLink'><a href='/myWork'>My Work</a></li>
              </ul>
            </div>
          </nav>

          {children}
      </main>
    </div>
  )


}

module.exports = layout;