import Head from 'next/head'
import { BsFillMoonStarsFill, BsGithub, BsLinkedin } from 'react-icons/bs'
import Image from "next/image"
import multiNote from "../public/multiNote.png"

import Cards from "../components/cards.js"

export default function Home() {
  return (
    <div >
      <Head>
        <title>Ruben Wilson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-2 flex justify-between'>
              <h1 className='bg-red-800 text-white px-4 py-2 rounded-lg mr-41'> MyCv </h1>
              <div className= 'flex mt-2 ml-40 cursor-pointer text-2xl '>
                <a className='mx-2'><BsFillMoonStarsFill /></a >
                <a className='mx-2'>< BsGithub /></a>
                <a className='ml-2'>< BsLinkedin /></a>
              </div>
          </nav>
          <div className='grid place-items-center '>
            <h1 className='text-red-700 text-9xl'>Ruben Wilson</h1>
            <h3 className=' pb-4 text-5xl text-gray-700'>Software Developer</h3>
            <div className='max-w-[60em]'>
              <p className='leading-6 text-sm  text-gray-600'>A twenty-year-old junior developer who is highly enthusiastic and driven. After spending nearly two years of my life preparing for the Marines, I never expected to find myself excited to start something new. Sustaining an injury in the Royal Marine's commando training, I was left with a fractured shoulder and I needed to find intellectual and physical stimulation which would fulfil my thirst for a challenge and importantly, also provide me with qualifications for a profession in which I would enjoy and be successful in.  </p>
            </div>
            <h2 className='text-5xl text-gray-700 mt-20 '>Projects:</h2>
          
          </div>

          <div className='grid place-items-center'>
            < Cards />
          </div>
        </section>

        


      </main>

   
    </div>
  )
}
