import Head from 'next/head'
import { BsFillMoonStarsFill, BsGithub, BsLinkedin } from 'react-icons/bs'

import Cards from "../components/cards.js"

export default function Home() {
  return (
    <div >
      <Head>
        <title>Ruben Wilson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-2 flex justify-between'>
            <a href='https://github.com/ruben-wilson/CV/blob/master/Makers%20CV-%20Software%20Engineer%20.pdf' className='bg-red-800 text-white px-4 py-2 max-h-10 rounded-lg mr-41'> MyCv </a>
            <h1 className='text-red-700 text-9xl pb-10 ml-[13rem]'>Ruben Wilson</h1>
              <div className= 'flex mt-2 ml-40 cursor-pointer text-2xl '>
                <a className='mx-2'><BsFillMoonStarsFill /></a >
              <a href='https://github.com/ruben-wilson' className='mx-2'>< BsGithub /></a>
              <a href='https://www.linkedin.com/in/ruben-wilson-6a774a254/' className='ml-2'>< BsLinkedin /></a>
              </div>
          </nav>
          <div className='grid place-items-center '>
            <h3 className=' pb-10 text-5xl text-gray-600'>Software Developer</h3>
            <div className='grid place-items-center max-w-[60em]'>
              <p className='leading-6 text-sm  text-gray-500'>A twenty-year-old developer who is highly enthusiastic and driven. After spending nearly two years of my life preparing for the Marines, I never expected to find myself excited to start something new. Sustaining an injury in the Royal Marine's commando training, I was left with a fractured shoulder and I needed to find intellectual and physical stimulation which would fulfil my thirst for a challenge. Luckily I found Coding.</p>
              <p className='leading-6 text-sm  text-gray-500'>Follow me to see where my journey goes!</p>
            </div>
            <h2 className='text-5xl text-gray-600 pt-[3rem]'>Projects:</h2>
          
          </div>

          <div className='grid place-items-center'>
            < Cards />
          </div>
        </section>

        


      </main>

   
    </div>
  )
}
